"""add variant to cart items

Revision ID: 20bb0cd26f3b
Revises: 91405b15a14b
Create Date: 2026-09-03 04:47:29.656432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bb0cd26f3b'
down_revision: Union[str, Sequence[str], None] = '91405b15a14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('variant_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_cart_items_cart_product'), 'cart_items', type_='unique')
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_variant_id'), table_name='cart_items')
    op.create_unique_constraint(op.f('uq_cart_items_cart_product'), 'cart_items', ['cart_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cart_items', 'variant_id')
    # ### end Alembic commands ###
