"""create sub_categories table

Revision ID: 5ff729518a6c
Revises: c713ee3a30af
Create Date: 2026-08-17 01:56:34.512797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff729518a6c'
down_revision: Union[str, Sequence[str], None] = 'c713ee3a30af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_categories_category_id'), 'sub_categories', ['category_id'], unique=False)
    op.create_index('uq_sub_categories_category_slug', 'sub_categories', ['category_id', 'slug'],unique=True,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sub_categories_category_slug', table_name='sub_categories')
    op.drop_index(op.f('ix_sub_categories_category_id'), table_name='sub_categories')
    op.drop_table('sub_categories')
    # ### end Alembic commands ###
