"""add user roles

Revision ID: 91405b15a14b
Revises: 101cbb00b321
Create Date: 2026-08-28 03:40:54.436938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91405b15a14b'
down_revision: Union[str, Sequence[str], None] = '101cbb00b321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_role = sa.Enum(
    "ADMIN",
    "CUSTOMER",
    name="user_role",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role, nullable=False, server_default='CUSTOMER'),)
    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role.drop(op.get_bind(), checkfirst=True,)
    # ### end Alembic commands ###
