"""change products to sub categories

Revision ID: e4eee695da73
Revises: 5ff729518a6c
Create Date: 2026-08-17 20:50:27.289379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4eee695da73'
down_revision: Union[str, Sequence[str], None] = '5ff729518a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sub_category_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_index(op.f('ix_products_sub_category_id'), 'products', ['sub_category_id'], unique=False)
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key("fk_products_sub_category_id", "products", "sub_categories", ["sub_category_id"], ["id"],)    
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_sub_categories_slug'), table_name='sub_categories')
    op.create_unique_constraint('uq_sub_categories_category_slug', 'sub_categories', ['category_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sub_categories_category_slug', 'sub_categories', type_='unique')
    op.create_index(op.f('ix_sub_categories_slug'), 'sub_categories', ['slug'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_products_sub_category_id", "products", type_="foreignkey",)
    op.create_foreign_key("fk_products_category_id", "products", "categories", ["category_id"], ["id"],)
    op.drop_index(op.f('ix_products_sub_category_id'), table_name='products')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.drop_column('products', 'sub_category_id')
    # ### end Alembic commands ###
