services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    restart: unless-stopped

    env_file:
      - ../.env.production

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]

    networks:
      - cartflow_network

  db:
    image: postgres:15

    restart: unless-stopped

    env_file:
      - ../.env.production

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - cartflow_network

volumes:
  postgres_data:

networks:
  cartflow_network:
    driver: bridge